In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
adults = df[(df['age'] >= 18) & (df['fare'] > 30)]
adults.head

<bound method NDFrame.head of      survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
1           1       1  female  38.0      1      0   71.2833        C   First
3           1       1  female  35.0      1      0   53.1000        S   First
6           0       1    male  54.0      0      0   51.8625        S   First
13          0       3    male  39.0      1      5   31.2750        S   Third
23          1       1    male  28.0      0      0   35.5000        S   First
..        ...     ...     ...   ...    ...    ...       ...      ...     ...
848         0       2    male  28.0      0      1   33.0000        S  Second
856         1       1  female  45.0      1      1  164.8667        S   First
867         0       1    male  31.0      0      0   50.4958        S   First
871         1       1  female  47.0      1      1   52.5542        S   First
879         1       1  female  56.0      0      1   83.1583        C   First

       who  adult_male deck  embark_town alive  alone
1    woman       False    C    Cherbourg   yes  False
3    woman       False    C  Southampton   yes  False
6      man        True    E  Southampton    no   True
13     man        True  NaN  Southampton    no  False
23     man        True    A  Southampton   yes   True
..     ...         ...  ...          ...   ...    ...
848    man        True  NaN  Southampton    no  False
856  woman       False  NaN  Southampton   yes  False
867    man        True    A  Southampton    no   True
871  woman       False    D  Southampton   yes  False
879  woman       False    C    Cherbourg   yes  False

[164 rows x 15 columns]>

In [9]:
df['family_size'] = df['sibsp'] + df['parch'] + 1
df[['sibsp' , 'parch', 'family_size']].head()

   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1

In [13]:
df['fare_per_person'] = df['fare'] / df['family_size']

In [20]:
df[['fare', 'family_size', 'fare_per_person']].head()

      fare  family_size  fare_per_person
0   7.2500            2          3.62500
1  71.2833            2         35.64165
2   7.9250            1          7.92500
3  53.1000            2         26.55000
4   8.0500            1          8.05000

In [16]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'family_size', 'fare_per_person'],
      dtype='str')

In [17]:
df.groupby(['pclass' , 'sex'])['fare'].mean()

pclass  sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

In [18]:
df.groupby(['pclass','sex']) ['survived'].mean()

pclass  sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: survived, dtype: float64

In [19]:
analysis = df.groupby(['pclass','sex']).agg({
    'fare': 'mean',
    'survived':'mean'
})
analysis

                     fare  survived
pclass sex
1      female  106.125798  0.968085
       male     67.226127  0.368852
2      female   21.970121  0.921053
       male     19.741782  0.157407
3      female   16.118810  0.500000
       male     12.661633  0.135447